export const AuthActionType = {
    INIT: 'AUTH_ACTION__INIT',
    LOGIN_SUCCESS: 'AUTH_ACTION__LOGIN_SUCCESS',
    GET_CURRENT_USER: 'AUTH_ACTION__GET_CURRENT_USER',
    GET_CURRENT_USER_SUCCESS: 'AUTH_ACTION__GET_CURRENT_USER_SUCCESS',
  };
  